import catchErrors from "../utils/catchErrors";

const registerHandler = catchErrors(async (req, res) => {
  // validate request
  // call service
  // return response
});

export { registerHandler };
